package com.immigrant.theimmigrantdreambackend.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ImmigrantBusiness")
public class ImmigrantBusiness {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    private String businessDescription;
    private String businessLocation;
    private String businessName;
    private String businessType;
    private String businessWebsite;
}
